### ISSUE TITLE
use problom

### ISSUE THREAD

**Issue by uptoheart** [20tab/django-totalsum-admin#2]
@admin.register(CustmOrderDetail)
class CustmOrderDetailAdmin(TotalsumAdmin):
    list_display = ('dtalorderMakeNo','dtalPrdnName','dtalPercent','dtalKg','dtalg','dtalmg','dtalres')
    totalsum_list = ('dtalKg','dtalg','model_property')
    unit_of_measure = '&euro;'

-------------------------------------------

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/formula/custmorderdetail/
2.0.3
TypeError
context must be a dict rather than Context.

**Comment by bitingmidge** [comment]
Looks like it needs updated for Django 1.11.

Line 34 of templatetags/totalsum.py should be changed from:
`return t.render(Context(c))`

to:
`return t.render(c)`

**Comment by uptoheart** [comment]
has been solved,Thanks!

**Comment by uptoheart** [comment]
has been solved,Thanks!

**Comment by gabbork** [comment]
Hi, if you updated this library locally to work with Django 1.11+ please do a merge request.
We'll work on a Django2+ py3+ update soon, otherwise. Thanks
