### ISSUE TITLE
Hi is django 2.2 not supported anymore?

### ISSUE THREAD

**Issue by rollue** [20tab/django-totalsum-admin#6]
I tried to pipenv-install the package but the dependency tree seems to be broken.

I currently use django 2.2.11(the LTS version) for my project, but this packages seems to support 3.0+ only. Would it be possible to support the 2.2? Thanks.

**Comment by rafleze** [comment]
Hi @mhoonjeon ,
please, check this url: https://pypi.org/project/django-totalsum-admin/1.0.0/
